### ISSUE TITLE
features of bytetrack_realtime?

### ISSUE THREAD

**Issue by HanGuangXin** [yhsmiley/bytetrack_realtime#1]
Hi there, Thanks for your work!

But I want to know the difference with the origin ByteTrack. Is your method faster than the origin ByteTrack?

**Comment by yhsmiley** [comment]
Hi, the functions in this repo are actually taken from the original ByteTrack repo. You can think of this repo as a wrapper for the ByteTrack module for running on real-time videos (e.g. webcam), with input bounding boxes from your own object detector.
