### ISSUE TITLE
give a example clearly

### ISSUE THREAD

**Issue by zxq309** [yhsmiley/bytetrack_realtime#2]
for example ：yolov5 + bytetrack

**Comment by yhsmiley** [comment]
I have an example usage [here](https://github.com/yhsmiley/streamlit_cv/blob/a80b0f49cfa26d39f846047dbe90a29787b1a584/misc/utils.py#L41) using ScaledYOLOv4 detector. But you can use any other detector as long as the input format to the tracker is the same.
