### ISSUE TITLE
Detect stopped object

### ISSUE THREAD

**Issue by MyraBaba** [yhsmiley/bytetrack_realtime#6]
Hi,

Thanks for the repo and codes.

Is there any indication that object is moving or not last 5 sec ? Looking a convenient way to do this.

Is there any parameter showing the movement in the returning tracks ?

Best

@yhsmiley

**Comment by yhsmiley** [comment]
@MyraBaba Hi, currently there is no support to show the movement of tracks, as this is not needed for ByteTrack to work.
